name: Reusable workflow for build and test.

on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.target }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
    - run: rustup component add llvm-tools
    - run: sudo apt update && sudo apt install libudev-dev
    - name: Build
      run: cargo build --release --verbose
    - name: Build examples
      run: cargo build --examples --release --verbose
    - name: Run tests
      run: |
        cargo test --release --verbose 2>&1 | tee stderr.txt
    - name: Check that tests failed for the expected reason
      run: '< stderr.txt grep -q "Error: unable to find Flipper Zero"'
