name: Update Bindings

on:
  workflow_dispatch:
    inputs:
      sdk_version:
        description: flipperzero-firmware SDK version
        type: string
        required: true

jobs:
  sdk:
    name: Update SDK bindings
    runs-on: ubuntu-latest
    permissions:
      # SAFETY: A commit authored by the Bot will be pushed
      contents: write
      # SAFETY: An update PR will be created by the Bot
      pull-requests: write
    steps:
      -
        name: Validate SDK version
        run: echo '${{ github.event.inputs.sdk_version }}' | grep --perl-regexp '^\d+\.\d+\.\d+$'
      -
        name: Checkout sources
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@18ce135bb5112fa8ce4ed6c17ab05699d7f3a5e0 # v3.11.0
      -
        name: Create branch
        run: git checkout -b'github-actions/update-bindings/sdk/${{ github.event.inputs.sdk_version }}'
      -
        name: Generate bindings
        id: generate-bindings
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          load: true
          build-args: 'BRANCH=${{ github.event.inputs.sdk_version }}'
          file: tools/Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        name: Copy bindings
        run: |
          container="$(docker container create ${{ steps.generate-bindings.outputs.imageid }} --read-only)"
          docker container cp "${container}":bindings.rs ./crates/sys/src/bindings.rs
          docker container rm "${container}"
      -
        name: Commit changes
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git commit crates/sys/src/bindings.rs \
            --message='build(bindings): bump SDK to `${{ github.event.inputs.sdk_version }}`'
      -
        name: Push changes
        run: git push --set-upstream origin 'github-actions/update-bindings/sdk/${{ github.event.inputs.sdk_version }}'
      -
        name: Create update Pull Request
        run: |
          gh pr create \
            --repo='flipperzero-rs/flipperzero' \
            --base='main' \
            --title='build(bindings): bump SDK to `${{ github.event.inputs.sdk_version }}`' \
            --body="${PULL_REQUEST_DESCRIPTION}" \
            --label='sdk-update'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_DESCRIPTION: >-
            # Description


            This updates SDK bindings to [`${{ github.event.inputs.sdk_version }}`][1].


            ---


            This PR has been automatically created by user @${{ github.triggering_actor }}
            via `${{ github.workflow }}` workflow.


            Further changes may added to this pull request.


            [1]: https://github.com/flipperdevices/flipperzero-firmware/releases/tag/${{ github.event.inputs.sdk_version }}
